HRPayroll/Models/ViewModels/EditAttendence.cs
using HRPayroll.Models.DomainModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRPayroll.Models.ViewModels
{
    public class EditAttendence
    {
        
        public List<EmployeeList> empList { get; set; }
        public List<Role> Role {get;set;}
        
        public IEnumerable<ViewList> view { get; set; }
        public int ListId { get; set; }
        public List<Update> List { get; set; }
        public SelectList OrganizationList { get; set; }
        public SelectList DepartmentList { get; set; }
        public string DepartmentName { get; set; }
        public int? OrganisationId { get; set; }
        public int? DepartmentId { get; set; }
        public SelectList AttendenceList { get; set; }
        public DateTime date { get; set; }
        public int Id { get; set; }
        public int? Emp_Id { get; set; }
        public int Att_ID { get; set; }
        public string AttName { get; set; }

        public IEnumerable<Attendence> Att { get; set; }
    }

    public class EmployeeList
    {
        public int AttendenceId { get; set; }
        public DateTime DOB { get; set; }
        public string Emergency_C { get; set; }
        public int ListId { get; set; }
        public string Gender { get; set; }
        public string H_F_Name { get; set; }
        public string Email { get; set; }
        public int EmpId { get; set; }
        public int Id { get; set; }
        public string Name { get; set; }
        public int DeptId { get; set; }
        public int OrgId { get; set; }
        public int? Emp_Id { get; set; }
        public string DeptName { get; set; }

        public string OrgName { get; set; }
        public string Phone { get; set; }

        public string Mother_Name { get; set; }

        public string Father_Name { get; set; }
        public string Address { get; set; }

        public string Aadhar_Number { get; set; }
        public int Att_ID { get; set; }

        public string AttendenceName { get; set; }
    }
        public class Update
        {

            public DateTime date { get; set; }
        
            public int? Emp_Id { get; set; }
            public int Att_ID { get; set; }
        public string Name { get; set; }
        public int DeptId { get; set; }
        public int OrgId { get; set; }
        public SelectList AttendenceList { get; set; }
        public int Id { get; set; }
    }

    public class ViewList
    {
        public string Name { get; set; }
        public string AttendenceName { get; set; }
        public int att_Id { get; set; }

    }
    }

HRPayroll/Models/ViewModels/IssueAdvance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRPayroll.Models.ViewModels
{
    public class IssueAdvance
    {

        public int Emp_Id { get; set; }//Foreign key
        public int EmpId { get; set; }
        public string Name { get; set; }
        public double? Issue_Advance { get; set; }
        public decimal? Advance_Due { get; set; }

        public int? OrganisationId { get; set; }

        public int? DepartmentId { get; set; }
         public SelectList OrganizationList { get; set; }


        public DateTime? Dated { get; set; }

        public IList<AdvanceIssue> IssueAdv { get; set; }
        public int OrgId { get; set; }
        public int DeptId { get; set; }
        public string OrgName { get; set; }

        public string DeptName { get; set; }
        public decimal Balance { get; set; }
        public DateTime? AdjustedDate { get; set; }

        public string Remarks { get; set; }
    }
}

HRPayroll/Controllers/SemiController.cs
using AutoMapper;
using HRPayroll.Models.DomainModels;
using HRPayroll.Models.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HRPayroll.Controllers
{
    [Authorize(Roles = "SemiAdmin")]
    public class SemiController : Controller
    {
        DBEntities ent = new DBEntities();

        public ActionResult semi()
        {
            return View();
        }
        [HttpGet]
        public ActionResult CreateEmployee()
        {
            var model = new EmployeeDTO();
            //model.DepartmentId = new SelectList(ent.Departments.ToList(), "DeptId", "DeptName");
            model.OrganizationList = new SelectList(ent.Organisations.ToList(), "OrgId", "OrgName");
            return View(model);
        }
        [HttpPost]
        public ActionResult CreateEmployee(EmployeeDTO model)

        {
            try
            {
                if (!ModelState.IsValid)
                {
                    //model.Department = new SelectList(ent.Departments.ToList(), "DeptId", "DeptName");
                    model.OrganizationList = new SelectList(ent.Organisations.ToList(), "OrgId", "OrgName");
                    return View(model);
                }
                var emp = Mapper.Map<Employee>(model);
                emp.IsDeleted = false;
                ent.Employees.Add(emp);
                ent.SaveChanges();
                TempData["msg"] = "Successfully Added";
                return RedirectToAction("CreateEmployee");
            }
            catch(Exception ex) {
                TempData["msg"] = "Server Error";
                return RedirectToAction("CreateEmployee");
            }
}

        public ActionResult EditAttendence(EditAttendence model)
        {
            model.AttendenceList = new SelectList(ent.Atendences.ToList(), "Id", "Attendence");
            string sqlQuery = "select EmpId as Id,Name,DeptId, OrgId from employee";
            var emp = ent.Database.SqlQuery<EmployeeList>(sqlQuery).ToList();
            if (model != null && model.OrganisationId != null && model.DepartmentId != null)
                emp = emp.Where(a => a.OrgId == model.OrganisationId && a.DeptId == model.DepartmentId).ToList();
            model.empList = emp;
            model.OrganizationList = new SelectList(ent.Organisations.ToList(), "OrgId", "OrgName");
            model.DepartmentList = new SelectList(ent.Departments.ToList(), "DeptId", "DeptName");
            //Filter For Attendence 
            return View(model);
        }

        public ActionResult SaveAttendance(Attendence model)
        {
            string msg = "";
            try
            {
                //var attendanceMaster = ent.Atendences.Find(model.att_Id);
                var record = ent.Attendences.FirstOrDefault(a => a.Emp_Id == model.Emp_Id && a.Date == model.Date);
                if (record == null)
                {
                    ent.Attendences.Add(model);
                }
                else
                {

                    record.att_Id = model.att_Id;
                }
                ent.SaveChanges();
                msg = "ok";
            }
            catch (Exception ex)
            {
                msg = "error";
            }
            return Json(msg, JsonRequestBehavior.AllowGet);
        }


        public ActionResult CasualLeave(LeavesRetrunModel model, int pageNumber = 1)
        {
            model.Departments = new SelectList(ent.Departments.ToList(), "DeptId", "DeptName");
            model.Organisation = new SelectList(ent.Organisations.ToList(), "OrgId", "OrgName");
            DateTime today = DateTime.Today;
            var data = (from e in ent.Employees
                        join leave in ent.LeavesLedgers
                        on e.EmpId equals leave.Emp_Id into g
                        select new empLeave
                        {

                            Emp_Id = e.EmpId,
                            Name = e.Name,
                            Phone = e.Phone,
                            Address = e.Address,
                            Email = e.Email,
                            Gender = e.Gender,
                            Emergency_C = e.Emergency_C,
                            Casual_Leave = g.Sum(leave => leave.Casual_Leave),

                            availCL = g.Sum(leave => leave.availCL),
                            //salId=s.Id
                        }).ToList();
            int totalRecord = data.Count;
            int pageSize = 5;
            double totalPages = Math.Ceiling((double)totalRecord / pageSize);
            data = data.Skip(pageSize * (pageNumber - 1)).Take(pageSize).ToList();
            model.PageNumber = pageNumber;
            model.TotalPages = Convert.ToInt32(totalPages);
            if (model != null && model.OrgId != null && model.DeptId != null)
                data = data.Where(a => a.OrgId == model.OrgId && a.DeptId == model.DeptId).ToList();
            model.empList = data;
            return View(model);
        }
   

        public ActionResult MarkCl(int id)
        {
            var model = new LeavesRetrunModel();
            var data = (from e in ent.Employees
                        join leaves in ent.LeavesLedgers on e.EmpId equals leaves.Emp_Id into g
                        where e.EmpId == id
                        select new empLeave
                        {
                            Emp_Id = e.EmpId,
                            Name = e.Name,
                            availCL = g.Sum(leaves => leaves.availCL),
                            Casual_Leave = g.Sum(leaves => leaves.Casual_Leave)
                        }).ToList();
            model.empList = data;
            return View(model);
        }


        [HttpPost]
        public ActionResult MarkCl(LeavesRetrunModel model)
        {
            var mark = Mapper.Map<LeavesLedger>(model);
            mark.Dated = DateTime.Now;
            mark.IsDeleted = false;
            mark.Emp_Id = model.Emp_Id;
            ent.LeavesLedgers.Add(mark);
            ent.SaveChanges();
            return RedirectToAction("CasualLeave", new { id = model.Emp_Id });

        }


        public ActionResult IssueAdvance(string term)
        {

            var model = new IssueAdvance();
            //model.OrganizationList = new SelectList(ent.Organisations.ToList(), "OrgId", "OrgName");
            var data = (from emp in ent.Employees
                        join empSal in ent.empSalaries on emp.EmpId equals empSal.Emp_Id into g
                        select new AdvanceIssue
                        {
                            Emp_Id = emp.EmpId,
                            Name = emp.Name,
                            Issue_Advance = g.Sum(empSal => empSal.Issue_Advance),
                            Advance_Due = g.Sum(empSal => empSal.Advance_Due)
                        }).ToList();
            //if (model != null && model.OrganisationId != null && model.DepartmentId != null)
            //    data = data.Where(a => a.OrganisationId == model.OrganisationId && a.DepartmentId == model.DepartmentId).ToList();
            if (!string.IsNullOrEmpty(term))
            {
                data = data.Where(a => a.Name.StartsWith(term)).ToList();
            }
            model.IssueAdv = data;
            return View(model);
        }


        //Mark Advance of an Employee
        public ActionResult markAdvance(int Empid)
        {
            var model = new IssueAdvance();
            var data = (from emp in ent.Employees
                        join empSal in ent.empSalaries on emp.EmpId equals empSal.Emp_Id into e
                        where emp.EmpId == Empid
                        select new AdvanceIssue
                        {
                            Emp_Id = emp.EmpId,
                            Name = emp.Name,
                            Issue_Advance = e.Sum(empSal => empSal.Issue_Advance),
                            Advance_Due = e.Sum(empSal => empSal.Advance_Due)
                        }).ToList();
            model.IssueAdv = data;
            return View(model);


        }


        [HttpPost]
        public ActionResult markAdvance(IssueAdvance model)
        {
            var mark = Mapper.Map<empSalary>(model);
            mark.Dated = DateTime.Now;
            mark.IsDeleted = false;
            mark.Emp_Id = model.Emp_Id;
            ent.empSalaries.Add(mark);
            ent.SaveChanges();
            return RedirectToAction("IssueAdvance", new { Empid = model.Emp_Id });
        }

        public ActionResult GetDepartmentsByOrgId(int OrgnisationId)
        {
            var dpt = ent.Departments.Where(a => a.OrgId == OrgnisationId).ToList();
            var data = Mapper.Map<IEnumerable<DepartmentDTO>>(dpt);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewAttendece()
        {
            int Month = DateTime.Now.Month;

            // Create List
            List<EmployeeAtt> empWithDate = new List<EmployeeAtt>();

            using (var ent = new DBEntities())
            {
                empWithDate = ent.Attendences.Where(a => a.Date.Value.Month == Month)
                     .Select(a =>
                     new EmployeeAtt
                     {
                         EmpId = a.Id,
                         Date = a.Date,
                         Attendence = a.Atendence.Attendence
                     }).OrderBy(a => a.Date).ToList();

            }

            return View(empWithDate);
        }

        public ActionResult ViewAdvance(IssueAdvance model)
        {
            string query = @"select  emp.Name, Sum(empSal.Issue_Advance) as TotalIssueAdvance, Sum(empSal.Advance_Due) as TotalAdvanceDue from empSalary empSal join Employee emp on empSal.EmpId = emp.EmpId group by EMP.Name";
            var data = ent.Database.SqlQuery<AdvanceIssue>(query).ToList();

HRPayroll/Views/Semi/CasualLeave.cshtml
@model HRPayroll.Models.ViewModels.LeavesRetrunModel


@{
    ViewBag.Title = "CasualLeave";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>CasualLeave</h2>*@
<h2>Mark CL of Employee</h2>

<div style="width:50%">
    @using (Html.BeginForm())
    {
        <div class="row" style="margin-left: 3%;
    margin-top: 2%;">
            <div class="form-group">
                Organization: @Html.DropDownListFor(x => x.OrganisationId, Model.OrganizationList, "Select Organization", new { @class = "", style = "width=3.25rem" })
            </div>
            <div class="form-group" style="margin-left: 2%;">
                Department: @Html.DropDownListFor(x => x.DepartmentId, Enumerable.Empty<SelectListItem>(), "Select Department", new { @class = "", style = "width=3.25rem" })
            </div>
            <div class="form-group" style="margin-left: 2%;">
                <input type="submit" id="btnSubmit" class="btn btn-primary" value="Filter" />
                <a href="/User/DepartmentSearch" class="btn btn-primary">All</a>
            </div>
        </div>
    }

</div>



@{
    int totalavailCL = Model.availCL;

}
<h3>Employees</h3>
@if (Model.empList.Count() < 1)
{
    <h5>No record found</h5>
}
else
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Phone</th>
                <th>Address</th>
                <th>Email</th>
                <th>Gender</th>
                <th>Emergency_C</th>
                <th>Avail CL</th>
                <th>Encashed CL</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.empList)
                {
                <tr>
                    <td id="@item.Emp_Id">@item.Name</td>
                    <td>@item.Phone</td>
                    <td>@item.Address</td>
                    <td>@item.Email</td>
                    <td>@item.Gender</td>
                    <td>@item.Emergency_C</td>

                    <td>@item.availCL</td>
                    <td>@item.Casual_Leave</td>
                    <td><a href="MarkCl?id=@item.Emp_Id">Mark CL</a></td>

                </tr>
            }
        </tbody>
    </table>
    <nav aria-label="Page navigation example">
        <ul class="pagination">
            @* <li class="page-item"><a class="page-link" href="#">Previous</a></li>*@
            @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    if (i == Model.PageNumber)
                    {
                    <li class="page-item active"><a class="page-link" href="/Admin/CasualLeave?pageNumber=@i">@i</a></li>

                }
                else
                {
                    <li class="page-item"><a class="page-link" href="/Admin/CasualLeave?pageNumber=@i">@i</a></li>

                }
            }
            @*<li class="page-item"><a class="page-link" href="#">Next</a></li>*@
        </ul>
    </nav>


    <div class="form-group">
        @if (TempData["msg"] != null)
        {
            <span style="color:green">@TempData["msg"]</span>
        }
    </div>
}
</div>
<script src="~/scripts/jquery-1.12.4.min.js"></script>

<script>
    $("#OrganisationId").change(function () {
        debugger
        var OrganisationId = $(this).val();
        var deptId = $("#DepartmentId");
        deptId.empty();
        deptId.append("<option value=''> Select Department </option>");
        $.ajax({
            url: "/User/GetDepartmentsByOrgId?OrgnisationId=" + OrganisationId,
            type: "get",
            success: function (response) {
                //  console.log(response);
                //$.each(response, function (key, value) {
                //    deptId.append("<option value= '" + value.DeptId + "'>" + value.DeptName + "</option>");

                //});
                if (response.length > 0) {
                    for(let i=0;i<response.length;i++)
                    {
                        deptId.append("<option value= '" + response[i].DeptId + "'>" + response[i].DeptName + "</option>");

                    }
                }
            },
            error: function(error){

                console.log(error.responseText);
            }
        });
    });

</script>

HRPayroll/Views/Semi/CreateEmployee.cshtml
@model HRPayroll.Models.ViewModels.EmployeeDTO
@{
    ViewBag.Title = "Employee";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("CreateEmployee", "Semi", FormMethod.Post, new { id = "frmEmp" }))
{

    <div style="width:50%;margin:auto">
        <h4>Employee Details</h4>
        <div class="form-group">
            Name: @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Name)</span>
        </div>

        <div class="form-group">
            Date of Birth: @Html.TextBoxFor(x => x.DOB, new { @class = "form-control datepicker", placeholder = "Date Format: DD/MM/YYYY" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.DOB)</span>

        </div>
        <div class="form-group">
            Joining Date: @Html.TextBoxFor(x => x.Joining_Date, new { @class = "form-control datepicker", placeholder = "Date Format: DD/MM/YYYY" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Joining_Date)</span>
        </div>

        <div class="form-group">
            Organization: @Html.DropDownListFor(x => x.OrgId, Model.Organtizations, "Select Organization", new { @class = "form-control", style = "width=3.25rem" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.OrgId)</span>

        </div>
        <div class="form-group">
            Department: @Html.DropDownListFor(x => x.DeptId, Model.Department, "Select Department", new { @class = "form-control", style = "width=3.25rem" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.DeptId)</span>

        </div>
        <div class="form-group">
            Gender: @Html.DropDownList("Gender", new List<SelectListItem>() { new SelectListItem() { Text = "Male", Value = "Male" }, new SelectListItem() { Text = "Female", Value = "Female", }
               }, "Select Gender", new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Gender)</span>
        </div>
        <div class="form-group">
            Address: @Html.TextBoxFor(x => x.Address, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Address)</span>
        </div>
        <div class="form-group">
            Phone: @Html.TextBoxFor(x => x.Phone, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Phone)</span>

        </div>
        <div class="form-group">
            Mother's Name: @Html.TextBoxFor(x => x.Mother_Name, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Mother_Name)</span>
        </div>
        <div class="form-group">
            Father's Name: @Html.TextBoxFor(x => x.Father_Name, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Father_Name)</span>
        </div>
        <div class="form-group">
            Husband's/Wife Name: @Html.TextBoxFor(x => x.H_F_Name, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.H_F_Name)</span>

        </div>
        <div class="form-group">
            EmailID: @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Email)</span>
        </div>
        <div class="form-group">
            Emergency Conatct: @Html.TextBoxFor(x => x.Emergency_C, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Emergency_C)</span>
        </div>
        <div class="form-group">
            Aadhaar Number: @Html.TextBoxFor(x => x.Aadhar_Number, new { @class = "form-control" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.Aadhar_Number)</span>
        </div>

        @if (TempData["msg"] != null)
        {
            <div class="form-group">
                @TempData["msg"]
            </div>
        }

        <div class="form-group">
            <input type="submit" id="btnSubmit" class="btn btn-primary" value="Save" />
        </div>
        
    </div>
}


<link href="/Content/themes/base/jquery-ui.min.css" rel="stylesheet" />

<link href="/Content/themes/base/jquery-ui.css" rel="stylesheet" />

    


    <script type="text/javascript">

     $(document).ready(function () {
         $(".datepicker").datepicker();

     });
    </script>

<script>
    $("#btnSubmit").click(function () {
        var CurrentBtn = $(this);
        var msg = $("#msg");
        CurrentBtn.attr("disabled", "disabled");
        msg.text("wait...");
        var frmData = $("#frmEmp").Serialize
    });
</script>



  

HRPayroll/Views/Semi/EditAttendence.cshtml
@model HRPayroll.Models.ViewModels.EditAttendence

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div style="width:50%; margin:auto;">
    @using (Html.BeginForm())
    {<div>
        <div class="form-group">
            Organization: @Html.DropDownListFor(x => x.OrganisationId, Model.OrganizationList, "Select Organization", new { @class = "form-control", style = "width=3.25rem" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.OrganisationId)</span>
        </div>
        <div class="form-group">
            Department: @Html.DropDownListFor(x => x.DepartmentId, Model.DepartmentList, "Select Department", new { @class = "form-control", style = "width=3.25rem" })
            <span style="color:red"> @Html.ValidationMessageFor(x => x.DepartmentId)</span>

        </div>
        <div class="form-group">
            <input type="submit" class="btn btn-primary" value="Filter" />
        </div>
    </div>

    }

    <h3>Employees Attendence</h3>
    @if (Model.empList.Count() < 1)
    {
        <h5>No record found</h5>
    }
    else
    {
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Attendence</th>
                    <th>Date</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.empList)
                {
                    <tr>
                        <td>
                            <input id="id" type="hidden" value="@item.Id" />
                            @item.Name
                        </td>
                        <td>
                            @Html.DropDownList("Att_Id", Model.AttendenceList, "Select Any", new { @class = "form-control attendance", id = "Att_Id" })
                        </td>
                        <td><input id="date" type="date" class="form-group" /></td>
                        <td>
                            @*<img id="pic" src=""  style="display:none;height:20px;width:20px" />*@
                            <input type="button" class="btn btn-info btnAttendanceSubmit" value="submit" />
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <span id="msg1"></span>

    }
</div>

<script src="/scripts/jquery-1.12.4.js"></script>
<script>
    $(".btnAttendanceSubmit").click(function () {debugger
        var current = $(this);
        current.val("wait..");
        current.attr('disabled', 'disabled');
        //var img = current.siblings("#pic");
        //img.attr('src', '/images/loader.png');
        //img.show();
        var id = current.parent().siblings().find("#id").val();
        var att_id = current.parent().siblings().find('#Att_Id').val();
        var date = current.parent().siblings().find('#date').val();
        var frmData= JSON.stringify({
            EmpId:id,
            att_Id:att_id,
            Date:date
        });
        $.ajax({
            url: '/Admin/SaveAttendance',
            type: 'post',
            contentType:'application/json',
            data:frmData,
        }).then(function (response) {
            console.log(response);
            if (response == 'ok') {
                current.val('Saved');
            }
                //img.attr('src', '/images/correct.png');
            else {
                current.val('error');
                //img.attr('src', '/images/cancel.png');
                current.removeAttr("disabled");

            }

        }, function (error) {
            //img.attr('src', '/images/cancel.png');
            console.log(error.responseText);

        });
        // img.hide();


    });
</script>


@*<script>
        $("#btnSubmit").click(function () {
            var currentBtn = $(this);
            var msg = $("#msg");
            currentBtn.attr("disabled", "disabled");
            msg.text("wait...");
            var frmData = $("#frmEmp").serialize();
            $.ajax({
                url: '/Admin/EditAttendence',
                type: 'post',
                data: frmData,
                success:function(response)
                {
                    if(response=="ok")
                    {
                        msg.text("Successfully added").css("color", "green");
                        $("input[type='text']").val("");
                    }
                    else
                    {
                        msg.text(response).css("color", "red");
                    }
                    currentBtn.removeAttr("disabled");
                },
                error:function(response)
                {
                    msg.text("Internal server error").css("color", "red");
                    currentBtn.removeAttr("disabled");
                    console.log(response.responseText);
                }
            });
        });
    </script>*@

HRPayroll/Views/Semi/IssueAdvance.cshtml
@model HRPayroll.Models.ViewModels.IssueAdvance
@{
    ViewBag.Title = "IssueAdvance";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="text-align:center">Issue Advance</h2>
<div style="margin:auto; width:80%;">
    @using (Html.BeginForm())
    {
        <div class="row">
            <div class="col-md-4">
                <input name="term" placeholder="Search by name" class="form-control" />
            </div>
            <div class="col-md-2">
                <input type="submit" value="Search" class="btn btn-info" />
                <a href="/Semi/IssueAdvance" class="btn btn-primary">All</a>
            </div>

            @*<div class="col-md-1"><a href="/Product/Add" class="btn btn-primary">Add more</a></div>*@
        </div>
    }
</div>
    @*<div class="row" style="margin-left: 3%;
    margin-top: 2%;">
        <div class="form-group">
            Organization: @Html.DropDownListFor(x => x.OrganisationId, Model.OrganizationList, "Select Organization", new { @class = "" })
        </div>
        <div class="form-group" style="margin-left: 2%;">
            Department: @Html.DropDownListFor(x => x.DepartmentId, Enumerable.Empty<SelectListItem>(), "Select Department", new { @class = "" })
        </div>
        <div class="form-group" style="margin-left: 2%;">
            <input type="submit" id="btnSubmit" class="btn btn-primary" value="Filter" />
            <a href="/Admin/DepartmentSearch" class="btn btn-primary">All</a>
        </div>
    </div>*@
}

<div class="row" style="margin:auto; width:80%;">
    @Html.HiddenFor(a => a.EmpId)
    <table class="table table-striped">
        <tr>
            <th>Employee Name</th>
            <th>Issue Advance(Total)</th>
            <th>Advance Due(Total)</th>
            <th>Action</th>
        </tr>
        <tbody>
            @foreach (var item in Model.advIssue)
            {

                <tr>
                    <td>
                        <input type="hidden" value="@item.Emp_Id" />
                        @item.empName
                    </td>
                    <td>@item.Issue_Advance</td>
                    <td>@item.AdvanceDue</td>
                    <td><a href="/Admin/markAdvance?Empid=@item.Emp_Id" class="btn btn-primary">Change</a></td>

                </tr>

            }

        </tbody>
    </table>

</div>

<script src="~/scripts/jquery-1.12.4.min.js"></script>
<script>
    $("#OrganisationId").change(function () {
        var OrganisationId = $(this).val();
        var deptId = $("#DepartmentId");
        deptId.empty();
        deptId.append("<option value=''> Select Department </option>");
        $.ajax({
            url: "/Semi/GetDepartmentsByOrgId?OrgnisationId=" + OrganisationId,
            type: "get",
            success: function (response) {
                //  console.log(response);
                //$.each(response, function (key, value) {
                //    deptId.append("<option value= '" + value.DeptId + "'>" + value.DeptName + "</option>");

                //});
                if (response.length > 0) {
                    for(let i=0;i<response.length;i++)
                    {
                        deptId.append("<option value= '" + response[i].DeptId + "'>" + response[i].DeptName + "</option>");

                    }
                }
            },
            error: function(error){

                console.log(error.responseText);
            }
        });
    });

</script>